cloud: k3s

image:
  tag: latest

ingress:
  type: nginx
  hostname: test.yourcloud.net
  path: /*
  letsencrypt: false
  nginx:
    enabled: false

clickhouseOperator:
  enabled: true
  namespace: default
  storage: 2Gi

web:
  secureCookies: false
  progressDeadlineSeconds: 1200

plugins:
  replicacount: 1
  progressDeadlineSeconds: 1200

worker:
  replicacount: 1
  progressDeadlineSeconds: 1200

redis:
  usePassword: false
  password: ""
  master:
    persistence:
      size: 1Gi
